# Generated by Django 2.2.2 on 2019-08-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('idI', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('Telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('Servicios', models.TextField(verbose_name='Servicios')),
                ('Informacion', models.TextField(verbose_name='Información')),
                ('Logo', models.ImageField(null=True, upload_to='fotos', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Inmobiliaria',
                'verbose_name_plural': 'Inmobiliarias',
                'ordering': ['-Nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaRenta',
            fields=[
                ('idVR', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Venta Renta')),
                ('Categoria', models.CharField(max_length=7, verbose_name='Categoria')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
                ('FechaP', models.DateField(auto_now_add=True, verbose_name='Fecha Publicación')),
                ('FechaM', models.DateField(auto_now_add=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Venta Renta',
                'verbose_name_plural': 'Ventas Rentas',
                'ordering': ['-FechaP'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Propiedad')),
                ('Tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('NoCuartos', models.CharField(max_length=5, verbose_name='Numero de Cuartos')),
                ('Telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('Correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('Banios', models.CharField(max_length=3, verbose_name='Baños')),
                ('Estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('Ciudad', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('Calle', models.CharField(max_length=60, verbose_name='Calle')),
                ('Colonia', models.CharField(max_length=60, verbose_name='Colonia')),
                ('No', models.CharField(max_length=5, verbose_name='Numero')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('FotoUno', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoDos', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoTres', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoCuatro', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('idI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Inmobiliaria', verbose_name='Clave Inmobiliaria')),
                ('idVR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.VentaRenta', verbose_name='Clave Venta Renta')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-Titulo'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idH', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Hotel')),
                ('Categoria', models.CharField(max_length=15, verbose_name='Categoria')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('NoHabitacion', models.CharField(max_length=5, verbose_name='Numero de Habitación')),
                ('NoCuartos', models.CharField(max_length=5, verbose_name='Numero de Cuartos')),
                ('Telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('Correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('Banios', models.CharField(max_length=3, verbose_name='Baños')),
                ('Estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('Ciudad', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('Calle', models.CharField(max_length=60, verbose_name='Calle')),
                ('Colonia', models.CharField(max_length=60, verbose_name='Colonia')),
                ('No', models.CharField(max_length=5, verbose_name='Numero')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('FotoUno', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoDos', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoTres', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('FotoCuatro', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('idVR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.VentaRenta', verbose_name='Clave Venta Renta')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['-Nombre'],
            },
        ),
    ]
