# Generated by Django 2.2.2 on 2019-08-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Persona', models.CharField(max_length=50, verbose_name='Correo')),
                ('Comentario', models.TextField(verbose_name='Comentario')),
                ('idH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Hotel', verbose_name='Clave Hotel')),
                ('idP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Propiedad', verbose_name='Clave Propiedad')),
            ],
        ),
    ]
